services:
  - type: web
    name: study-tool
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn student.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: 'False'
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: study-tool-db
          property: connectionString

databases:
  - name: study-tool-db
    plan: free # Change to a paid plan if needed for persistence
