# Generated by Django 5.2.5 on 2025-08-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('mobile_number', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('qualification', models.CharField(max_length=50)),
            ],
        ),
    ]
