# Generated by Django 5.2.5 on 2025-08-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='register',
            name='last_name',
            field=models.CharField(default='Mehta', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='middle_name',
            field=models.CharField(default='Bhaveshbhai', max_length=50),
            preserve_default=False,
        ),
    ]
